# This is the "Light blue square" from the paper
f_layer_thickness : 200000
xfe_outer_core : 0.83
growth_prefactor : 150.0
i0 : 1.0e-11
surf_energy : 1.08
wetting_angle : 5.0
number_of_analysis_points : 100
number_of_knots : 5
r_icb : 1221500
r_cmb : 3480000
gruneisen_parameter : 1.5
chemical_diffusivity : 1.0e-9
kinematic_viscosity : 2.0e-6
thermal_conductivity : 100.0
max_time : 1.0E20
hetrogeneous_radius : 10.0e-10
